# Generated by Django 4.0.4 on 2022-05-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='platfrom',
            new_name='platform',
        ),
    ]
