# Generated by Django 4.0.4 on 2022-05-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_platfrom_order_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='查询条件')),
                ('objs', models.ManyToManyField(blank=True, to='dashboard.order')),
            ],
            options={
                'verbose_name': '查询记录',
            },
        ),
    ]
